### ISSUE TITLE
Is va in trainer/pre.py referred to val_acc_averager?

### ISSUE THREAD

**Issue by CookieLau** [y2l/meta-transfer-learning-pytorch#1]
Thanks for your contribution first!
When I'm running your pytorch implementation code, I found that i was stuck at pre-train since the va in trainer/pre.py is not defined, it should be Average class in utils/misc.
![image](https://user-images.githubusercontent.com/30521971/62822209-eca01e00-bbb2-11e9-8dda-8dba7a851b89.png)
I read your code and found that val_acc_averager might be never updated in the whole process, so is my guessing correct?
![image](https://user-images.githubusercontent.com/30521971/62822265-967faa80-bbb3-11e9-8eee-fdb539899872.png)

Thank you for your reply in advance.

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

Your guess is correct.

Our PyTorch code is based on [FEAT](https://github.com/Sha-Lab/FEAT). In order to be more understandable, I changed several variables' names. However, that may cause some bugs. This bug is fixed now.
